// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Infrastructure.Repository;

#nullable disable

namespace WebApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240829113958_AddPortTerminalRelationship")]
    partial class AddPortTerminalRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Data.Models.PortDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5546),
                            Code = "ABCDE",
                            LastEditedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5541),
                            Name = "Port A"
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5548),
                            Code = "FGHIJ",
                            LastEditedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5547),
                            Name = "Port B"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Models.TerminalDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEditedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("Name", "PortId")
                        .IsUnique();

                    b.ToTable("Terminals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5645),
                            IsActive = true,
                            Latitude = 40.712800000000001,
                            Longitude = -74.006,
                            Name = "Terminal 1",
                            PortId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2024, 8, 29, 11, 39, 58, 402, DateTimeKind.Utc).AddTicks(5647),
                            IsActive = true,
                            Latitude = 34.052199999999999,
                            Longitude = -118.2437,
                            Name = "Terminal 2",
                            PortId = 2
                        });
                });

            modelBuilder.Entity("WebApi.Infrastructure.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("WebApi.Data.Models.TerminalDto", b =>
                {
                    b.HasOne("WebApi.Data.Models.PortDto", "Port")
                        .WithMany("Terminals")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Port");
                });

            modelBuilder.Entity("WebApi.Data.Models.PortDto", b =>
                {
                    b.Navigation("Terminals");
                });
#pragma warning restore 612, 618
        }
    }
}
